# This workflow will install dependencies, check for dependency version consistency, build all packages in the repo, and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: PR Build

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install
        name: 'install package source and devDeps'
      - run: npm run build
        name: 'build'
      - run: npm test
        name: 'run tests'
