trigger:
- release/*

pool:
  name: iModelTechCI

steps:
- checkout: self
  clean: true
- task: NodeTool@0
  displayName: "install Node 10.16.x"
  inputs:
    versionSpec: "10.16.x"
    checkLatest: true
- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc
- script: npm install
  displayName: 'install package source and devDeps'
- script: npm run build
  displayName: 'build bundle'
# TODO: verify that broken tests will not publish
- script: npm test
  displayName: 'run tests'
- script: npm publish
  displayName: 'publish'

