trigger:
- release/*

pool:
  name: iModelTechCI

steps:
- checkout: self
  clean: true
- task: NodeTool@0
  displayName: "install Node 10.16.x"
  inputs:
    versionSpec: "10.16.x"
    checkLatest: true
- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc
- script: npm install --production
  displayName: 'install build dependencies'
- script: npm install --save-dev typescript@4.1.3
  displayName: 'install packages required to perform build'
- script: npm run build
  displayName: 'build bundle'
# TODO: verify that broken tests will not publish
- script: npm test
  displayName: 'run tests'
- script: npm publish
  displayName: 'publish'

