trigger:
- release/*

pool:
  name: ubuntu-latest

steps:
- checkout: self
  clean: true
- task: NodeTool@0
  displayName: "install Node 10.16.x"
  inputs:
    versionSpec: "10.16.x"
    checkLatest: true
- script: npm install
  displayName: 'install package source and devDeps'
- script: npm run build
  displayName: 'build bundle'
- script: npm test
  displayName: 'run tests'
- script: npm publish
  displayName: 'publish'

