# PR CI pipeline

# only trigger on PRs
trigger: none

pr:
  drafts: false
  branches:
    include:
    - master
    - release/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  clean: true
- task: NodeTool@0
  displayName: "install Node 10.16.x"
  inputs:
    versionSpec: "10.16.x"
    checkLatest: true
- script: npm install
  displayName: 'install package source and devDeps'
- script: npm run build
  displayName: 'build bundle'
- script: npm test
  displayName: 'run tests'

