# publish pipeline

trigger:
- release/*

pool:
  name: iModelTechCI

steps:
- task: NodeTool@0
  displayName: "install Node 16.14.x"
  inputs:
    versionSpec: "16.14.x"
    checkLatest: true

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc

- script: npm install --production
  displayName: 'install package dependencies'

- script: npm install --save-dev webpack webpack-cli
  displayName: install packages required to perform build

- script: npm run build:bundle
  displayName: build bundle

- script: npm publish
  displayName: publish

